import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Link from 'next/link';
import ImgCard from '../comps/ImgCard';



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/boiler">Go to boiler</Link>

      <ImgCard
        bg="FDE8CA">
        <h3>This is a children</h3>
        morestuff<hr />
        yay
      </ImgCard>

      <ImgCard
        img="https://placekitten.com/300/300"
        text="this is a cat"
        tcl="ABC980"
      />


    </div>

  )
}